# data : pubmed, citeseer, cora, Cornell, Texas, Wisconsin, Photo, Computers 
data:
  data: cora
  dir: './data'
  nfeat: 1433
  nlabel: 7

# temp: temperatures in constructing a buffer
diffusion:
  method: Continuous
  step: 20
  s: 0.001
  coef: 1
  temp: 0.3

model:
  model: GCNConv
  denoise_model: v1
  nhid: 64
  num_layers: 1
  num_linears: 1
  skip: True

# load_start: number of iterations in initial maximization step
# load_interval: number of iterations in maximization step
train:
  load_start: 2000
  num_epochs: 2000
  pre_train_epochs: 100
  lr_simple: 0.005
  print_interval: 50
  load_interval: 30
  time_batch: 32
  lr_schedule: True
  lr: 0.005
  weight_decay: 0.0005
  grad_norm: 1
  lr_decay: 0.99999
  eps: 1.0e-5