# data : pubmed, citeseer, cora, Cornell, Texas, Wisconsin, Photo, Computers 
data:
  data: physics   
  dir: './data'
  nfeat: 8415
  nlabel: 5

# temp: temperatures in constructing a buffer
diffusion:
  method: Continuous
  step: 10
  s: 0.0001
  coef: 1
  temp: 0.3

model:
  model: GCNConv
  denoise_model: v1
  nhid: 64
  num_layers: 1
  num_linears: 1
  skip: False

# load_start: number of iterations in initial maximization step
# load_interval: number of iterations in maximization step
train:
  load_start: 2000
  num_epochs: 500
  pre_train_epochs: 1000
  lr_simple: 0.01
  print_interval: 1
  load_interval: 100
  time_batch: 4
  lr_schedule: True
  lr: 0.005
  weight_decay: 0.01
  grad_norm: 1
  lr_decay: 0.99999
  eps: 1.0e-5